### PR TITLE
Add validators match check

### LINKED ISSUE #3: List of validators must be the same on both sides of the bridge
Consider to have the check in the monitoring tool which allow to monitor list of authorities on both sides of the bridge. The tool should report the list of authorities on both sides and results of comparison - there must not be any validator which exists on one side of the bridge but absent on another.

Requires #7

### PR DESCRIPTION
**Pull request by patitonar**
Closes #3 

Add a new attribute for `/validators`: `validatorsMatch` will be true if the list of validators is the same on both sides and false if it is not. Also validators that are only on one side, will have a property `onlyOnHome` or  `onlyOnForeign` depending on the side.

Example with same list of validators:
```
{
    "home": {
        "validators": {
            "0x3752F0a521b2E383693f658D6FC377953024C207": {
                "balance": "8.528009755331",
                "leftTx": 28426699184436,
                "gasPrice": 1
            }
        }
    },
    "foreign": {
        "validators": {
            "0x3752F0a521b2E383693f658D6FC377953024C207": {
                "balance": "1.426323768362",
                "leftTx": 1981,
                "gasPrice": 2.4
            }
        }
    },
    "validatorsMatch": true,
    "lastChecked": 1539801120
}
```

Example with different list of validators:
```
{
    "home": {
        "validators": {
            "0x3752F0a521b2E383693f658D6FC377953024C207": {
                "balance": "8.528009755331",
                "leftTx": 28426699184436,
                "gasPrice": 1
            },
            "0xf4BEF13F9f4f2B203FAF0C3cBbaAbe1afE056955": {
                "balance": "5.126058159704",
                "leftTx": 17086860532346,
                "gasPrice": 1,
                "onlyOnHome": true
            }
        }
    },
    "foreign": {
        "validators": {
            "0x3752F0a521b2E383693f658D6FC377953024C207": {
                "balance": "1.426323768362",
                "leftTx": 2377,
                "gasPrice": 2
            },
            "0xbb140FbA6242a1c3887A7823F7750a73101383e3": {
                "balance": "1.589855539534",
                "leftTx": 2649,
                "gasPrice": 2,
                "onlyOnForeign": true
            }
        }
    },
    "validatorsMatch": false,
    "lastChecked": 1539800932
}

```

### CODE REVIEW

**Comment by akolotov** [comment]
@fernandomg could you resolve the merge issue?

**Comment by fernandomg** [comment]
> @fernandomg could you resolve the merge issue?

Done

**Comment by fernandomg** [comment]
> Please consider to move checks for requiredSignatures from / endpoint to the /validators endpoint. It is more logical to have it here.

@akolotov @patitonar this has to be done or will be part of a different issue?

**Comment by fernandomg** [comment]
> > @akolotov @patitonar this has to be done or will be part of a different issue?
> 
> How long it could take to address this?

Done. Updated README.md as well.

Output examples:
`/`
```json
{
    "home": {
        "balance": "1.4999999998999",
        "deposits": 3,
        "withdrawals": 2
    },
    "foreign": {
        "totalSupply": "0.75",
        "deposits": 4,
        "withdrawals": 2
    },
    "balanceDiff": 0.7499999998999,
    "lastChecked": 1544017360,
    "depositsDiff": -1,
    "withdrawalDiff": 0
}
```

`/validators`
```json
{
    "home": {
        "validators": {
            "0x3634fFa16f904fe7e40Cb61f5787a3A25909D579": {
                "balance": "0.830119864908921071",
                "leftTx": 2767066216363,
                "gasPrice": 1
            }
        },
        "requiredSignatures": 1
    },
    "foreign": {
        "validators": {
            "0x3634fFa16f904fe7e40Cb61f5787a3A25909D579": {
                "balance": "1.913373843087970268",
                "leftTx": 708,
                "gasPrice": 9
            }
        },
        "requiredSignatures": 1
    },
    "requiredSignaturesMatch": true,
    "validatorsMatch": true,
    "lastChecked": 1544017371
}
```

**Pull request merged**
